### ISSUE TITLE
Gazebo isn't loading map

### ISSUE THREAD

**Issue by AidanHolvik** [RobotnikAutomation/rbkairos_sim#16]
I am having an issue where the map is not being loaded to gazebo. I am running the simulation on Ubuntu 18.04 with with python 2.7. I am using gazebo version 9.0.0 and rviz version 1.13.24. The simulator was installed by following the steps given in the README.

The robot avoids obstacles which were present in the pre-generated map (used in rviz), but the obstacles are not represented in the gazebo simulation.

**Comment by scploeger** [comment]
Hey @alex-arnal,

Maybe it is worth noting that I am also running Ubuntu 18.04, Gazebo 9.0.0, ROS Melodic, Python 2.7.17. I created a new workspace folder and created a new vanilla workspace by following the instructions in the readme, however it appears that the simulation is working fine for me, the world appears in Gazebo as intended. 

So maybe there is something else that is causing incompatibility for @AidanHolvik.

**Comment by alex-arnal** [comment]
Hi @AidanHolvik,

Could you provide some output from Gazebo? It seems like there is a problem loading the Gazebo world (i.e. file does not exists). Maybe you could try to create a new vanilla workspace as @scploeger suggest.

**Comment by AidanHolvik** [comment]
Trying to load the world directly into gazebo doesn't work. Gazebo displays a blank map, and the terminal displays the following output:


Error Code: 11 Msg: Unable to find uri[madel://willowgarage]
[ERR] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'


It is worth noting that scploeger's computer was able to load the file into gazebo without issue by following the same process.

**Comment by scploeger** [comment]
Hey @alex-arnal @AidanHolvik I just tried:
`source /usr/share/gazebo/setup.sh` and now I can recreate @AidanHolvik original issue. 
The contents of `setup.sh` is now:

`
export GAZEBO_MASTER_URI=http://localhost:11345
export GAZEBO_MODEL_DATABASE_URI=http://gazebosim.org/models
export GAZEBO_RESOURCE_PATH=/usr/share/gazebo-9:${GAZEBO_RESOURCE_PATH}
export GAZEBO_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/gazebo-9/plugins:${GAZEBO_PLUGIN_PATH}
export GAZEBO_MODEL_PATH=/usr/share/gazebo-9/models:${GAZEBO_MODEL_PATH}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu/gazebo-9/plugins
export OGRE_RESOURCE_PATH=/usr/lib/x86_64-linux-gnu/OGRE-1.9.0
`

I guess there is some other gazebo setup script that needs to be sourced somewhere?

**Comment by alex-arnal** [comment]
The REST request issue should be solved with the following command:

sed -i 's/api.ignitionfuel.org/fuel.ignitionrobotics.org/g' ~/.ignition/fuel/config.yaml

But I don't know if that will solve the issue of not loading the Gazebo world.

**Comment by AidanHolvik** [comment]
That fixed the REST issue, but the world still won't load properly. Trying to directly load the world into gazebo only prints one line to the terminal now:

Error Code 11: Msg: Unable to find uri[model://willowgarage]


~/home/user/.gazebo/server-11345/default.log is displaying the following:

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ {some IP address that I don't know whether it's safe to share}
[Msg] Publicized address: {another ip address that might not be safe to share}
[Wrn] [ModelDatabase.cc:340] Getting models from[http://gazebosim.org/models/]. This may take a few seconds.
[Err] [ModelDatabase.cc:235] No <database> tag in the model database database.config found here[http://gazebosim.org/models/]
[Err] [ModelDatabase.cc:294] Unable to download model manifests
[Err] [ModelDatabase.cc:414] Unable to download model[model://willowgarage]
[Err] [SystemPaths.cc:412] File or path does not exist[""]
Init world[default]


when I run the following command:

echo $(find rbkairos_gazebo)

the following is printed to the terminal:

find: 'rbkairos_gazebo': No such file or directory
